language : go

os:
- linux
- osx

go:
- 1.8.x
- 1.9.x
- 1.10.x
- 1.11.x
- tip

go_import_path: go.bmvs.io/orderedset

sudo: false

before_install:
- go get -u github.com/mattn/goveralls
- go get -u github.com/golang/dep/cmd/dep
- dep ensure

script:
- go test -v -race ./...

after_success:
- goveralls -service=travis-ci

notifications:
  email:
    on_success: change
    on_failure: always
